name: Check runner state

on:
  repository_dispatch:
    types:
      - webhook
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/check-runner.yml"
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bun-version: [latest]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun ${{ matrix.bun-version }}
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}
      - name: Check "dig" command
        run: dig +short github.com

      - name: Adding markdown
        run: |
            cat << EOF >> $GITHUB_STEP_SUMMARY
            # 🚀
            - ✅ \`dig\`
            EOF
