name: Lint

on:
  repository_dispatch:
    types:
      - webhook
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/lint.yml"
      - "src/**/*.ts"
      - "src/**/*.tsx"
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bun-version: [latest]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun ${{ matrix.bun-version }}
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}
      - run: bun install
      - run: bunx tsc
